version: '3.8'

services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    restart: unless-stopped

  medical_app:
    build: .
    container_name: medical_app
    ports:
      - "8501:8501"
    volumes:
      - ./data:/app/data:ro
    environment:
      - PYTHONPATH=/app
    depends_on:
      - ollama
    restart: unless-stopped

volumes:
  ollama_data: